const books = [
    {
        id: 1,
        title: "Nhà Giả Kim",
        author: "Paulo Coelho",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBAQmtBJP7JT2PSVR4J562HT5cQHTI0brzl_vAnmtiQBNzFbvsdwULHLbHQSJ-XEIjTT4h70qrPMZKAQsmn5A9uqTkoh-WmrDLDMzB4-A08fcRa9_kZ7Nm22fJsw7AVBf9sTWN0WRqjOEXSr5j6xdlpeThhlXZogAE361c74d76EgFfDwREBd7T1PLHzpV_S5PLN6EkNx1bPwFqO0TkOhy-sk0aILEUVW6UbeNWyUF28TCQt9gvmXlOf2fEF1ZaG0OPtRbHWS9xzLUN",
        price: 125000,
        original_price: 150000,
        category: "Tiểu thuyết",
        rating: 4.5,
        description: "Cuốn sách kể về Santiago, một cậu bé chăn cừu người Andalusia, người có một giấc mơ lặp đi lặp lại về kho báu ở các kim tự tháp Ai Cập.",
        year: 1988,
        pages: 208,
        featured: true,
        promo: true
    },
    {
        id: 2,
        title: "Đắc Nhân Tâm",
        author: "Dale Carnegie",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBIwUkSra8dQ6Gxs46zK8jy7yNhPyCuw36lpSZA0opu5pUh54rl7RBfWK579scIjCDZxHRgW_L_-WP6t8kLaC1R-en44jHLHpgI0MzJaMo_6okcxs5sOG0FmHq7wUamydSsVzyg4JxYLa_TE5XMSzIRhsJeS9hsmrDJfHNJiApA8qGbTFOCOxTPFbAF7PwmCyGJUDRQSF1XRFlE-_hFNsmtBw6VkRZ06thPsor1oC7nCgTyBGYOrS1F6sPnPPP24K08jky33jnMC2wg",
        price: 99000,
        original_price: 120000,
        category: "Self-help",
        rating: 5,
        description: "Đây là cuốn sách về nghệ thuật giao tiếp và ứng xử đã được chứng minh là hiệu quả qua nhiều thế hệ.",
        year: 1936,
        pages: 320,
        featured: true,
        promo: true
    },
    {
        id: 3,
        title: "Muôn Kiếp Nhân Sinh",
        author: "Nguyên Phong",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAB0sgril5upMFqGNXvYbgY6e5Dm4od0jT77tioeXoC9QJC6DA9ZFaeMNM4S_OGlCY3CmzEoE08S7jrLxpxNsoYezOYHIfJbuQ7MENZ6fYXGRdKhXqDivQbj5grMznCH1epBdBu_o3X7cEUsj_Hr4iPsxFS2i35RMOCpIUeghuw9ib7_VdzR_kXC_7wMP42acz5h5eBzstZ8GSkDGiyRgwFGNhrpThtN9DvMemEywBALpKpmtcHXNFchzSsJxp1-F0hHrjRIi2XLcVI",
        price: 150000,
        original_price: null,
        category: "Tâm lý học",
        rating: 5,
        description: "Tác phẩm ghi lại những câu chuyện, trải nghiệm tiền kiếp của một doanh nhân tài chính ở New York.",
        year: 2020,
        pages: 444,
        featured: true,
        promo: false
    },
    {
        id: 4,
        title: "Cây Cam Ngọt Của Tôi",
        author: "José Mauro de Vasconcelos",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBewcxnOUznmUBn1kPkfsbP27r8e-xknCWJO0jPg7nkThN_Emk9Z5xlC7AnjpN6SiagZAxNtlxM_QGi7udwJdVY6O3wcO1HFGD_GxIJY5HgnpSDZ84bUu-bLI6Yw0mg8mEKi9t1bOp6DFN_aSGWv6ikez-Z0rDLt9X7tE5TasQr0yrBPVs3Yv4PxsHqLrCP5Z_q8Fx6eavOnTfIRnWbsMLwMpz5oMX3RIyNOXMRLMMfgXy_Xl2uSurHRu46VVoEdhQUlkZsFyRkUF4m",
        price: 85000,
        original_price: null,
        category: "Thiếu nhi",
        rating: 5,
        description: "Câu chuyện cảm động về Zezé, một cậu bé tinh nghịch nhưng giàu trí tưởng tượng và vô cùng nhạy cảm.",
        year: 1968,
        pages: 244,
        featured: true,
        promo: false
    },
    {
        id: 5,
        title: "Sapiens: Lược Sử Loài Người",
        author: "Yuval Noah Harari",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuD1cJQhozdVGoHasQFZ2MkIaeM0AxsVUGjCFFB0TbBZSinFTCDd3033wUz9WGD-qy7sXJYQhj0r-EmoMg27yMh5CgPkPyzsfg00jbxdYX1CJZ9djZ_V-miFrbkGUk9N2FbNGmypg2wzKcvD-KZ2dHFFJhuG67Pc1QNMpBI0Gd0EqNtI76T4imZE28z-fHcGdeoljgpVhmroDfe6T_sYxV3M82mbEMRyyuyIhnqw8SHUzsuzx0laIRJtsNI0a7wHEWV849EbvO1_8Ml5",
        price: 210000,
        original_price: null,
        category: "Học thuật",
        rating: 5,
        description: "Một cái nhìn tổng quan về lịch sử của loài người từ thời kỳ đồ đá cho đến thế kỷ 21.",
        year: 2011,
        pages: 512,
        featured: false,
        promo: true
    },
    {
        id: 6,
        title: "Tội Ác và Hình Phạt",
        author: "Fyodor Dostoevsky",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCaNjBl7vWcmP2GDyVtbMkPf7fzVrzXlxXXM3S5O0K8pUtIVx6lhE103fWFfqE4Cvz0Cqw_rOPzaneN-kyJ0AIzZcRnMsGMZTSFSjt_bqkIdB-yMt20y0MxsZ6JBFeuZS55CHpJb_5Vet3gzqszWnqISW-NEjY4ZLE47mfDZQa-QnwUj2lEzLhhAyhLDL-UX5Z7gMh8v3SaJZUiu8vvtUnDNYzfI_C9oF3Sb0TuWOKYtxtPfEbTC95QDRxFwhogYtI3mnsBHHqQfPX5",
        price: 180000,
        original_price: null,
        category: "Tiểu thuyết",
        rating: 4,
        description: "Câu chuyện về Rodion Raskolnikov, một sinh viên nghèo ở St. Petersburg, người đã lên kế hoạch và thực hiện một vụ giết người.",
        year: 1866,
        pages: 671,
        featured: false,
        promo: false
    },
    {
        id: 7,
        title: "Hoàng Tử Bé",
        author: "Antoine de Saint-Exupéry",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDSA4otLBVu4is71AYGWhIVbTUfvlDjU2u5A5lYhnzrp5ISPfBUGKii4jQnc4Eqn5YK8f66PMZY8k5fGtdL8lL6JgYQdTCSlZyHN0adw2CDgBgyRZuPmuQGjVcWiwy8R18-QTZFpreXh5hAc9nzNAHFxvLJusvkdgfXkksM_ZMBq7zzLPu77DpwjzTGG-iWg0mbIK6ick35CC2qfbPhJVfaZI7ehx_X8U9hbl-IhVGhGXS40IC3podN7XAPsEWqcqv2O4Mp-uCiSTHG",
        price: 70000,
        original_price: null,
        category: "Thiếu nhi",
        rating: 5,
        description: "Một câu chuyện ngụ ngôn về tình bạn, tình yêu, sự mất mát và sự cô đơn.",
        year: 1943,
        pages: 96,
        featured: false,
        promo: false
    },
    {
        id: 8,
        title: "Bố Già",
        author: "Mario Puzo",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDB5-_P_OUPyD4WV0VVRiZwejpDAom1Hz-ustuGpNmTN6FlWL0_0QSxpp3ECrwMW_7A5pnjqi3QIRcb4vm1GjQe9RXOw1x-fRxkTqMevpkMp9vQ0V2XAkDltLJp_WytSz0lmyb8tF7tHNEGtMt5adyBCGBqjZLF_8rLNeccaPbBQOPklCXlnITmll2-ywxmpZsZk7IWygynDj3R6nSgLKFljMgIrCdLO71xiqyMI-cfhZbWZKIH07MdCP7s__7gUSTmkEaCfsLVqvPC",
        price: 195000,
        original_price: null,
        category: "Tiểu thuyết",
        rating: 4.5,
        description: "Câu chuyện về gia đình mafia Corleone, tập trung vào nhân vật Michael Corleone và quá trình anh trở thành người đứng đầu gia đình.",
        year: 1969,
        pages: 448,
        featured: false,
        promo: false
    },
    {
        id: 9,
        title: "Tư Duy Nhanh và Chậm",
        author: "Daniel Kahneman",
        image: "https://salt.tikicdn.com/cache/w1200/ts/product/20/63/1c/c1a603956d351f0441b4b5785055b834.jpg",
        price: 250000,
        original_price: null,
        category: "Kinh tế",
        rating: 4.8,
        description: "Cuốn sách khám phá hai hệ thống tư duy của con người: Hệ thống 1 (nhanh, cảm tính) và Hệ thống 2 (chậm, logic).",
        year: 2011,
        pages: 640,
        featured: false,
        promo: false
    }
];

const categories = ["Tất cả", "Tiểu thuyết", "Self-help", "Tâm lý học", "Thiếu nhi", "Học thuật", "Kinh tế"];
